# Default values for user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  name: ecomm-ingress

userService:
  name: user-service
  image: user-service
  imageTag: latest
  service:
    type: ClusterIP
    portName: user-svc-port
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50

productService:
  name: product-service
  image: product-service
  imageTag: latest
  service:
    type: ClusterIP
    portName: prod-svc-port
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80    

orderService:
  name: order-service
  image: order-service
  imageTag: latest
  service:
    type: ClusterIP
    portName: order-svc-port
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80      
