apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.userService.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.userService.name }}
  minReplicas: {{ .Values.userService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.userService.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: 50
