apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
  labels:
    app: {{ .Values.userService.name }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.userService.service.portName }}
      protocol: TCP
  selector:
    app: {{ .Values.userService.name }}
