apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.userService.name }}
  labels:
    app: {{ .Values.userService.name }}
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.userService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.userService.name }}
    spec:
      containers:
        - name: {{ .Values.userService.name }}
          image: "{{ .Values.userService.image }}:{{ .Values.userService.imageTag }}"
          imagePullPolicy: Never
          ports:
            - name: {{ .Values.userService.service.portName }}
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.userService.service.portName }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.userService.service.portName }}
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
